name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  playwright:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
  
      - uses: pnpm/action-setup@v4
  
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
  
      - name: Install dependencies (Playwright tests)
        working-directory: tests/playwright
        run: pnpm install --frozen-lockfile
      - name: Build Next.js app
        run: pnpm build
      - name: Install Playwright Browsers
        working-directory: tests/playwright
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        working-directory: tests/playwright
        env:
          CI: true
        run: pnpm exec playwright test
